// Code generated by goctl. DO NOT EDIT.
package types

type AddReq struct {
	Book  string `form:"book"`
	Price int64  `form:"price"`
}

type AddResp struct {
	Ok bool `json:"ok"`
}

type CheckReq struct {
	Book string `form:"book"`
}

type CheckResp struct {
	Found bool  `json:"found"`
	Price int64 `json:"price"`
}

type HelmListReq struct {
	Release string `form:"release"`
}

type HelmListResp struct {
	ReleaseCount int              `json:"releaseCount"`
	Release      []*HelmListsResp `json:"release"`
}

type HelmListsResp struct {
	ReleaseName string `json:"release"`
	NameSpace   string `json:"nameSpace"`
	Revison     string `json:"revison"`
	UpDate      string `json:"upDate"`
	Status      string `json:"status"`
	Chart       string `json:"chart"`
}
