// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"friday/helmdeploy/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/add",
				Handler: AddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/check",
				Handler: CheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/helmlist",
				Handler: GetHelmListHandler(serverCtx),
			},
		},
	)
}
